language: julia
julia:
  - 0.7
  - 1.0

before_script:
  - julia -e 'using Pkg; 
              Pkg.add(PackageSpec(url="https://github.com/RJDennis/ChebyshevApprox.jl"))'
  - julia -e 'using Pkg; 
              Pkg.add(PackageSpec(url="https://github.com/RJDennis/SmolyakApprox.jl"))'
  - julia -e 'using Pkg; 
              Pkg.add(PackageSpec(url="https://github.com/RJDennis/PiecewiseLinearApprox.jl"))'

#script:
#    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - julia -e 'Pkg.clone(pwd()); Pkg.test("SolveDSGE", coverage=true)'
after_success:
  # push coverage results to Codecov
#  - julia -e 'cd(Pkg.dir("SolveDSGE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("SolveDSGE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
